//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QingZhiKu.UI.Designs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_zh_CNold {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_zh_CNold() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QingZhiKu.UI.Designs.Resource.zh-CNold", typeof(Resource_zh_CNold).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string CatAction {
            get {
                return ResourceManager.GetString("CatAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外观 的本地化字符串。
        /// </summary>
        internal static string CatAppearance {
            get {
                return ResourceManager.GetString("CatAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行为 的本地化字符串。
        /// </summary>
        internal static string CatBehavior {
            get {
                return ResourceManager.GetString("CatBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        internal static string CatData {
            get {
                return ResourceManager.GetString("CatData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string CatInformation {
            get {
                return ResourceManager.GetString("CatInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性已更改 的本地化字符串。
        /// </summary>
        internal static string CatPropertyChanged {
            get {
                return ResourceManager.GetString("CatPropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RightToLeft属性更改时发生 的本地化字符串。
        /// </summary>
        internal static string ControlOnRightToLeftLayoutChangedDescr {
            get {
                return ResourceManager.GetString("ControlOnRightToLeftLayoutChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外观 的本地化字符串。
        /// </summary>
        internal static string DesignerActionAppearanceItemDisplayName {
            get {
                return ResourceManager.GetString("DesignerActionAppearanceItemDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string DesignerActionInformationItemDisplayName {
            get {
                return ResourceManager.GetString("DesignerActionInformationItemDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每当绘制特定项/区域时发生 的本地化字符串。
        /// </summary>
        internal static string drawItemEventDescr {
            get {
                return ResourceManager.GetString("drawItemEventDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 无效的参数 {1} 的本地化字符串。
        /// </summary>
        internal static string InvalidArgument {
            get {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 无效的下限参数 {1} 的本地化字符串。
        /// </summary>
        internal static string InvalidLowBoundArgumentEx {
            get {
                return ResourceManager.GetString("InvalidLowBoundArgumentEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string PropertiesCategoryName {
            get {
                return ResourceManager.GetString("PropertiesCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectedIndex 属性发生更改时发生 的本地化字符串。
        /// </summary>
        internal static string selectedIndexChangedEventDescr {
            get {
                return ResourceManager.GetString("selectedIndexChangedEventDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TabControl 选中选项卡页序号 的本地化字符串。
        /// </summary>
        internal static string selectedIndexDescr {
            get {
                return ResourceManager.GetString("selectedIndexDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此选项卡将从中获取图像的ImageList对象 的本地化字符串。
        /// </summary>
        internal static string TabBaseImageListDescr {
            get {
                return ResourceManager.GetString("TabBaseImageListDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项卡数量 的本地化字符串。
        /// </summary>
        internal static string TabBaseTabCountDescr {
            get {
                return ResourceManager.GetString("TabBaseTabCountDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加选项卡 的本地化字符串。
        /// </summary>
        internal static string TabControlAdd {
            get {
                return ResourceManager.GetString("TabControlAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加选项卡头部 的本地化字符串。
        /// </summary>
        internal static string TabControlAddHeader {
            get {
                return ResourceManager.GetString("TabControlAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加选项卡到&apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string TabControlAddTab {
            get {
                return ResourceManager.GetString("TabControlAddTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在取消选择一个选项卡页作为最顶部的选项卡页之后发生 的本地化字符串。
        /// </summary>
        internal static string TabControlDeselectedEventDescr {
            get {
                return ResourceManager.GetString("TabControlDeselectedEventDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在取消选择选项卡页时发生 的本地化字符串。
        /// </summary>
        internal static string TabControlDeselectingEventDescr {
            get {
                return ResourceManager.GetString("TabControlDeselectingEventDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的选项卡页面类型 {0} 的本地化字符串。
        /// </summary>
        internal static string TabControlInvalidTabPageType {
            get {
                return ResourceManager.GetString("TabControlInvalidTabPageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除选项卡 的本地化字符串。
        /// </summary>
        internal static string TabControlRemove {
            get {
                return ResourceManager.GetString("TabControlRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除选项卡头部 的本地化字符串。
        /// </summary>
        internal static string TabControlRemoveHeader {
            get {
                return ResourceManager.GetString("TabControlRemoveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除选项卡从 &apos;{0}&apos; 到 &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string TabControlRemoveTab {
            get {
                return ResourceManager.GetString("TabControlRemoveTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除选项头框从 &apos;{0}&apos; 到 &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string TabControlRemoveTabHeader {
            get {
                return ResourceManager.GetString("TabControlRemoveTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在选择一个选项卡页作为最顶部的选项卡页之后发生 的本地化字符串。
        /// </summary>
        internal static string TabControlSelectedEventDescr {
            get {
                return ResourceManager.GetString("TabControlSelectedEventDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TabControl 选中选项卡页 的本地化字符串。
        /// </summary>
        internal static string TabControlSelectedTabDescr {
            get {
                return ResourceManager.GetString("TabControlSelectedTabDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在选择选项卡页时发生 的本地化字符串。
        /// </summary>
        internal static string TabControlSelectingEventDescr {
            get {
                return ResourceManager.GetString("TabControlSelectingEventDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TabControl 的 TabPages 的本地化字符串。
        /// </summary>
        internal static string TabControlTabsDescr {
            get {
                return ResourceManager.GetString("TabControlTabsDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项卡切换器 的本地化字符串。
        /// </summary>
        internal static string TabFormSwitcher {
            get {
                return ResourceManager.GetString("TabFormSwitcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项卡控件 的本地化字符串。
        /// </summary>
        internal static string TabFormSwitcherSelectedObject {
            get {
                return ResourceManager.GetString("TabFormSwitcherSelectedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TabControl的选项卡切换框区域 的本地化字符串。
        /// </summary>
        internal static string TabHeaderDescription {
            get {
                return ResourceManager.GetString("TabHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TabControl 头部选框 的本地化字符串。
        /// </summary>
        internal static string TabHeaderDisplayName {
            get {
                return ResourceManager.GetString("TabHeaderDisplayName", resourceCulture);
            }
        }
    }
}
