//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QingZhiKu.UI.WinForms.Designs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QingZhiKu.UI.WinForms.Designs.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        internal static string CatAction {
            get {
                return ResourceManager.GetString("CatAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance 的本地化字符串。
        /// </summary>
        internal static string CatAppearance {
            get {
                return ResourceManager.GetString("CatAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior 的本地化字符串。
        /// </summary>
        internal static string CatBehavior {
            get {
                return ResourceManager.GetString("CatBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string CatData {
            get {
                return ResourceManager.GetString("CatData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string CatInformation {
            get {
                return ResourceManager.GetString("CatInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe property changed 的本地化字符串。
        /// </summary>
        internal static string CatPropertyChanged {
            get {
                return ResourceManager.GetString("CatPropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe control on right to left layout changed 的本地化字符串。
        /// </summary>
        internal static string ControlOnRightToLeftLayoutChangedDescr {
            get {
                return ResourceManager.GetString("ControlOnRightToLeftLayoutChangedDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance 的本地化字符串。
        /// </summary>
        internal static string DesignerActionAppearanceItemDisplayName {
            get {
                return ResourceManager.GetString("DesignerActionAppearanceItemDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string DesignerActionInformationItemDisplayName {
            get {
                return ResourceManager.GetString("DesignerActionInformationItemDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe draw item event 的本地化字符串。
        /// </summary>
        internal static string drawItemEventDescr {
            get {
                return ResourceManager.GetString("drawItemEventDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid argument {0} {1} 的本地化字符串。
        /// </summary>
        internal static string InvalidArgument {
            get {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Invalid Low Bound Argument {1} 的本地化字符串。
        /// </summary>
        internal static string InvalidLowBoundArgumentEx {
            get {
                return ResourceManager.GetString("InvalidLowBoundArgumentEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        internal static string PropertiesCategoryName {
            get {
                return ResourceManager.GetString("PropertiesCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe SelectedIndex changed event 的本地化字符串。
        /// </summary>
        internal static string selectedIndexChangedEventDescr {
            get {
                return ResourceManager.GetString("selectedIndexChangedEventDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe selected index 的本地化字符串。
        /// </summary>
        internal static string selectedIndexDescr {
            get {
                return ResourceManager.GetString("selectedIndexDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe TabControl get image ImageList object 的本地化字符串。
        /// </summary>
        internal static string TabBaseImageListDescr {
            get {
                return ResourceManager.GetString("TabBaseImageListDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe TabControl Item count 的本地化字符串。
        /// </summary>
        internal static string TabBaseTabCountDescr {
            get {
                return ResourceManager.GetString("TabBaseTabCountDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Tab 的本地化字符串。
        /// </summary>
        internal static string TabControlAdd {
            get {
                return ResourceManager.GetString("TabControlAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add TabHeader 的本地化字符串。
        /// </summary>
        internal static string TabControlAddHeader {
            get {
                return ResourceManager.GetString("TabControlAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add tab to &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string TabControlAddTab {
            get {
                return ResourceManager.GetString("TabControlAddTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe TabControl deselected event 的本地化字符串。
        /// </summary>
        internal static string TabControlDeselectedEventDescr {
            get {
                return ResourceManager.GetString("TabControlDeselectedEventDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe TabControl deselecting event 的本地化字符串。
        /// </summary>
        internal static string TabControlDeselectingEventDescr {
            get {
                return ResourceManager.GetString("TabControlDeselectingEventDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TabControl Invalid TabPage Type {0} 的本地化字符串。
        /// </summary>
        internal static string TabControlInvalidTabPageType {
            get {
                return ResourceManager.GetString("TabControlInvalidTabPageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Tab 的本地化字符串。
        /// </summary>
        internal static string TabControlRemove {
            get {
                return ResourceManager.GetString("TabControlRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove TabHeader 的本地化字符串。
        /// </summary>
        internal static string TabControlRemoveHeader {
            get {
                return ResourceManager.GetString("TabControlRemoveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove tab &apos;{0}&apos; from &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string TabControlRemoveTab {
            get {
                return ResourceManager.GetString("TabControlRemoveTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove tabHeader &apos;{0}&apos; from &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string TabControlRemoveTabHeader {
            get {
                return ResourceManager.GetString("TabControlRemoveTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe TabControl selected event 的本地化字符串。
        /// </summary>
        internal static string TabControlSelectedEventDescr {
            get {
                return ResourceManager.GetString("TabControlSelectedEventDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe TabControl SelectedTab 的本地化字符串。
        /// </summary>
        internal static string TabControlSelectedTabDescr {
            get {
                return ResourceManager.GetString("TabControlSelectedTabDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe TabControl selecting event 的本地化字符串。
        /// </summary>
        internal static string TabControlSelectingEventDescr {
            get {
                return ResourceManager.GetString("TabControlSelectingEventDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe TabPages of TabControl 的本地化字符串。
        /// </summary>
        internal static string TabControlTabsDescr {
            get {
                return ResourceManager.GetString("TabControlTabsDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TabFormControlSwitcher 的本地化字符串。
        /// </summary>
        internal static string TabFormSwitcher {
            get {
                return ResourceManager.GetString("TabFormSwitcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TabFormControl 的本地化字符串。
        /// </summary>
        internal static string TabFormSwitcherSelectedObject {
            get {
                return ResourceManager.GetString("TabFormSwitcherSelectedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TabControl switch Tab panel 的本地化字符串。
        /// </summary>
        internal static string TabHeaderDescription {
            get {
                return ResourceManager.GetString("TabHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TabControl header panel 的本地化字符串。
        /// </summary>
        internal static string TabHeaderDisplayName {
            get {
                return ResourceManager.GetString("TabHeaderDisplayName", resourceCulture);
            }
        }
    }
}
